CREATE TABLE manifest
(
	IlmnID NVARCHAR(29) NULL,
	Name NVARCHAR(10) NULL,
	IlmnStrand NVARCHAR(3) NULL,
	SNP NVARCHAR(5) NULL,
	AddressAID NVARCHAR(10) NULL,
	AlleleAProbeSeq NVARCHAR(50) NULL,
	AddressBID NVARCHAR(1) NULL,
	AlleleBProbeSeq NVARCHAR(1) NULL,
	GenomeBuild NVARCHAR(4) NULL,
	Chr NVARCHAR(2) NULL,
	MapInfo NVARCHAR(9) NULL,
	Ploidy NVARCHAR(7) NULL,
	Species NVARCHAR(12) NULL,
	Source NVARCHAR(5) NULL,
	SourceVersion NVARCHAR(3) NULL,
	SourceStrand NVARCHAR(3) NULL,
	SourceSeq NVARCHAR(125) NULL,
	TopGenomicSeq NVARCHAR(125) NULL,
	BeadSetID NVARCHAR(3) NULL,
	ExpClusters NVARCHAR(1) NULL,
	RefStrand NVARCHAR(1) NULL
)
